databases:
  - name: flavorStart
    databaseName: flavorStart
    user: flavorStart

services:
  - type: web
    name: flavorStart
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: flavorStart
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
