databases:
  - name: flavorstar
    databaseName: flavorstar
    user: flavorstar

services:
  - type: web
    name: flavorstar
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: flavorstar
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
