databases:
  - name: flavor-star
    databaseName: flavor-star
    user: flavor-star

services:
  - type: web
    name: flavor-star
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: flavor-star
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
